<?php
/** @var \Dxc\Warning\Block\Html\Header\SmokelessWarning $block */
?>
<?php if ($block->isShow()): ?>
    <div class="dxc-smokeless-warning">
        <div class="clipped warning-container">
			<div id="page-warning" class="warning-wrapper sixty">
				<h1 class="warning-text">
					WARNING: This product contains nicotine. Nicotine is an addictive chemical.
				</h1>
			</div>
			<p class="warning-subtext">Vapor Products</p>
        </div>
    </div>
    
    <script type="text/javascript">
	/*
	We don't need this anymore
    require(['jquery'], function($){ 
        $(".dxc-smokeless-warning img").on('error', function(){
        	$.ajax({
                url: "<?php echo $block->getUrlDetection() ?>",
                type: 'GET',
                complete: function() {
                    location.reload();
                }
            });
        });
    });
	*/

    // From SagePath
    //To enable the fail safe we check the length of the warning element that holds the text.
    //If it is meets the condition (currently greater than 10 characters) reload and if not make the ajax call
    /*
    require(['jquery'], function($){ 
        var warningTextLength = $('.warning-text')[0].innerText.length;
        if(warningTextLength < 15) {
            console.log('Error: Failed to load warning text.');
            $.ajax({
                url: "<?php echo $block->getUrlDetection() ?>",
                type: 'GET',
                complete: function() {
                    location.reload();
                }
            });
        } else {
            console.log('Success');
        }
    });
    */
    </script>
    
    
<?php endif; ?>
